[2025-06-22 01:35:09,367] 123 __init__.py - INFO - Loaded config from Config_Yaml/classifiers.yaml
[2025-06-22 01:35:09,689] 123 __init__.py - INFO - Loaded config from Config_Yaml/config_path.yaml
[2025-06-22 01:35:09,691] 100 __init__.py - INFO - Running 'execute_model_tune_evaluate'...
[2025-06-22 01:35:09,691] 188 Model_Tune_Evaluate.py - INFO - Starting Classification Model Tuning...
[2025-06-22 01:35:09,806] 100 __init__.py - INFO - Running 'run_grid_search'...
[2025-06-22 01:35:09,851] 102 Model_Tune_Evaluate.py - INFO - Running Bayesian search for: logistic_regression
[2025-06-22 01:35:09,872] 106 Model_Tune_Evaluate.py - INFO - Starting Feature Engineering..
[2025-06-22 01:35:09,872] 110 Model_Tune_Evaluate.py - INFO - Feature selector and extractor initialized..
[2025-06-22 01:37:56,945] 119 Model_Tune_Evaluate.py - INFO - Feature Engineering completed..
[2025-06-22 01:37:56,945] 121 Model_Tune_Evaluate.py - INFO - Starting model tuning..
[2025-06-22 01:38:28,052] 137 Model_Tune_Evaluate.py - INFO - initial model tuning finished..
[2025-06-22 01:38:28,052] 139 Model_Tune_Evaluate.py - INFO - Starting model fine tuning on (train+val)..
[2025-06-22 01:38:28,149] 171 Model_Tune_Evaluate.py - ERROR - Bayesian search failed.
Traceback (most recent call last):
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 141, in run_grid_search
    X_val_extracted = prepare_features_for_model(self.X_val, encoder_scaler, selector, extractor, self.X_train.columns)
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 59, in prepare_features_for_model
    encoded = encoder_scaler.transform(raw_df)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\pipeline.py", line 1092, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\compose\_column_transformer.py", line 1090, in transform
    raise ValueError(f"columns are missing: {diff}")
ValueError: columns are missing: {'Total_Trans_Amt', 'Total_Ct_Chng_Q4_Q1', 'Dependent_count', 'Total_Amt_Chng_Q4_Q1', 'Income_Category', 'Education_Level', 'Contacts_Count_12_mon', 'Gender', 'Total_Trans_Ct', 'Months_on_book', 'Avg_Utilization_Ratio', 'Credit_Limit', 'Customer_Age', 'Total_Relationship_Count', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Marital_Status', 'Months_Inactive_12_mon', 'Card_Category'}
[2025-06-22 01:38:28,166] 194 Model_Tune_Evaluate.py - CRITICAL - Fatal error in classifier tuning pipeline.
[2025-06-22 01:38:28,166] 90 __init__.py - CRITICAL - Unhandled Exception
Traceback (most recent call last):
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 141, in run_grid_search
    X_val_extracted = prepare_features_for_model(self.X_val, encoder_scaler, selector, extractor, self.X_train.columns)
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 59, in prepare_features_for_model
    encoded = encoder_scaler.transform(raw_df)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\pipeline.py", line 1092, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\prasa\anaconda3\envs\mlp-env\lib\site-packages\sklearn\compose\_column_transformer.py", line 1090, in transform
    raise ValueError(f"columns are missing: {diff}")
ValueError: columns are missing: {'Total_Trans_Amt', 'Total_Ct_Chng_Q4_Q1', 'Dependent_count', 'Total_Amt_Chng_Q4_Q1', 'Income_Category', 'Education_Level', 'Contacts_Count_12_mon', 'Gender', 'Total_Trans_Ct', 'Months_on_book', 'Avg_Utilization_Ratio', 'Credit_Limit', 'Customer_Age', 'Total_Relationship_Count', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Marital_Status', 'Months_Inactive_12_mon', 'Card_Category'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 190, in execute_model_tune_evaluate
    tuner.run_grid_search()
  File "d:\ml_churn_prediction_mlops\Common_Utils\__init__.py", line 105, in wrapper
    result = func(*args, **kwargs)
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 172, in run_grid_search
    raise CustomException(e, sys)
Common_Utils.CustomException: Error in script: [D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py] at line [141] - Message: [columns are missing: {'Total_Trans_Amt', 'Total_Ct_Chng_Q4_Q1', 'Dependent_count', 'Total_Amt_Chng_Q4_Q1', 'Income_Category', 'Education_Level', 'Contacts_Count_12_mon', 'Gender', 'Total_Trans_Ct', 'Months_on_book', 'Avg_Utilization_Ratio', 'Credit_Limit', 'Customer_Age', 'Total_Relationship_Count', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Marital_Status', 'Months_Inactive_12_mon', 'Card_Category'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 199, in <module>
    execute_model_tune_evaluate()
  File "d:\ml_churn_prediction_mlops\Common_Utils\__init__.py", line 105, in wrapper
    result = func(*args, **kwargs)
  File "D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py", line 195, in execute_model_tune_evaluate
    raise CustomException(e, sys)
Common_Utils.CustomException: Error in script: [D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py] at line [190] - Message: [Error in script: [D:\ml_churn_prediction_mlops\src\Model_Tune_Evaluate.py] at line [141] - Message: [columns are missing: {'Total_Trans_Amt', 'Total_Ct_Chng_Q4_Q1', 'Dependent_count', 'Total_Amt_Chng_Q4_Q1', 'Income_Category', 'Education_Level', 'Contacts_Count_12_mon', 'Gender', 'Total_Trans_Ct', 'Months_on_book', 'Avg_Utilization_Ratio', 'Credit_Limit', 'Customer_Age', 'Total_Relationship_Count', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Marital_Status', 'Months_Inactive_12_mon', 'Card_Category'}]]
